export const GET_HISTORICAL_RATES = "GET_HISTORICAL_RATES";
export const SET_LIVE_RATES = "SET_LIVE_RATES";
export const SET_CURRENCIES = "SET_CURRENCIES";
export const SET_BASE_CURRENCY = "SET_BASE_CURRENCY";
export const SET_TARGET_CURRENCIES = "SET_TARGET_CURRENCIES";
export const IO_ERROR = "IO_ERROR";